package com.eduai.mailservice.api.mail;

import com.eduai.mailservice.dto.request.BulkEmailRequestDto;
import com.eduai.mailservice.dto.request.EmailRequestDto;
import com.eduai.mailservice.dto.request.OtpRequestDto;
import com.eduai.mailservice.dto.request.ScheduleEmailRequestDto;
import com.eduai.mailservice.dto.response.BulkEmailResponseDto;
import com.eduai.mailservice.dto.response.EmailResponseDto;
import com.eduai.mailservice.dto.response.OtpResponseDto;
import jakarta.validation.Valid;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * Mail API contract shared between client and server.
 *
 * <p>Server: implement this interface in MailController.
 * <p>Client: use OpenFeign with @FeignClient pointing to this interface.
 *
 * <p>Base path: /api/v1/mail
 */
@RequestMapping(value = "/api/v1/mail", produces = MediaType.APPLICATION_JSON_VALUE)
public interface MailApi {

    /**
     * Send a single email (transactional, welcome, reminder, promotional, etc.).
     * The email is asynchronously queued for processing.
     *
     * @param request Email send request
     * @return Accepted response with message ID
     */
    @PostMapping("/send")
    ResponseEntity<EmailResponseDto> sendEmail(@Valid @RequestBody EmailRequestDto request);

    /**
     * Send an OTP verification email.
     * OTP is generated by the service if not supplied in the request.
     *
     * @param request OTP send request
     * @return OTP send response with masked email and expiry info
     */
    @PostMapping("/send/otp")
    ResponseEntity<OtpResponseDto> sendOtp(@Valid @RequestBody OtpRequestDto request);

    /**
     * Send a bulk/broadcast email to multiple recipients.
     * Each recipient can have individual template variable substitution.
     *
     * @param request Bulk email request
     * @return Batch response with per-recipient status
     */
    @PostMapping("/send/bulk")
    ResponseEntity<BulkEmailResponseDto> sendBulkEmail(@Valid @RequestBody BulkEmailRequestDto request);

    /**
     * Schedule an email for future delivery.
     * Supports one-shot and recurring (cron) schedules.
     *
     * @param request Schedule request wrapping email payload and schedule config
     * @return Scheduled email response
     */
    @PostMapping("/schedule")
    ResponseEntity<EmailResponseDto> scheduleEmail(@Valid @RequestBody ScheduleEmailRequestDto request);

    /**
     * Retrieve the current status of a sent email by message ID.
     *
     * @param messageId UUID of the email message
     * @return Current email status and metadata
     */
    @GetMapping("/status/{messageId}")
    ResponseEntity<EmailResponseDto> getEmailStatus(@PathVariable String messageId);

    /**
     * Cancel a scheduled email.
     *
     * @param messageId UUID of the scheduled email
     * @return Cancellation response
     */
    @DeleteMapping("/schedule/{messageId}")
    ResponseEntity<EmailResponseDto> cancelScheduledEmail(@PathVariable String messageId);

    /**
     * Health check / ping endpoint.
     *
     * @return "pong"
     */
    @GetMapping("/ping")
    ResponseEntity<String> ping();
}
